### ISSUE TITLE
Links pointing to etherscan.io

### ISSUE THREAD

**Issue by jeffdoubleyou** [ubiq/sparrow-plugin#4]
It seems that the links to view your account and transactions are still going to etherscan.io instead of ubiqscan.io.

Also, the main net RPC address is still pointing to an Ethereum node, not sure if that's an oversight and one is ready or not.

**Comment by aldoborrero** [comment]
During my last merge of changes they already moved the configuration of networks (so your PR is right). I'll proceed to merge it.
